language: java

jdk:
  - oraclejdk8
 
addons:
  postgresql: "9.6"

services:
  - postgresql

travis_test:
  adapter: postgresql

cache:
  directories:
    - $HOME/.m2

script:
  - mvn -B -Dmaven.deploy.skip=true -Dmaven.javadoc.skip=true 